// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbhghuwatflynohbltu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YmhnaHV3YXRmbHlub2hibHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTQ4ODEsImV4cCI6MjA2NDQ3MDg4MX0.V5jTnFzWzOOQqVtqD9HtI8ORF7nsYtU_SI8gZq6iH3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);